---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-api-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/wachira90/xxxxxxx.git
    targetRevision: prod
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
